name: ${name}
version: ${version}
description: ${description}
authors: ${authors}
website: ${url}

main: ${mainClass}
api-version: ${apiVersion}
loadbefore:
  - msDecor
  - msUtils
  - msBlock
  - msItems
